appName: python-flask-app

image:
  repository: rajeshgoyalg/python-flask-app
  tag: v20250302-493a4a3
  pullPolicy: Always  # Ensures Kubernetes always pulls the latest image

replicas: 2
containerPort: 5000

service:
  type: NodePort
  port: 80
  targetPort: 5000